# Generated by Django 5.2.7 on 2025-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ManyToManyField(related_name='subjects', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
