# Generated by Django 5.2.7 on 2025-10-26 03:08

import django.db.models.deletion
import questionnaires.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=questionnaires.models.questionnaire_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('xls', 'Excel Spreadsheet (Legacy)'), ('txt', 'Text File')], max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='accounts.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='accounts.subject')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
